import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const authAPI = createApi({
    reducerPath: 'authApi',
    baseQuery: fetchBaseQuery({
        baseUrl: 'https://dummyjson.com/auth/'
    }),
    endpoints: (builder) => ({
        login: builder.mutation({
            query: (credentials) => ({
                url: 'login',
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(credentials)  // That's the username and password, also optional expiresInMins
                // Access token is valid for 30 minutes by default, can be requested otherwise
            })
        })
    })
})

// The name of the hooks are generated by RTK Query from endpoint names
export const { useLoginMutation } = authAPI